#@iina Shift+Meta+v video-panel
#@iina Shift+Meta+a audio-panel
#@iina Shift+Meta+s sub-panel
#@iina Shift+Meta+p playlist-panel
#@iina Shift+Meta+c chapter-panel
#@iina Meta+3 fit-to-screen
#@iina Meta+- smaller-window
#@iina Meta+= bigger-window
#@iina Ctrl+Meta+p toggle-pip
#@iina Alt+Meta+m toggle-music-mode
#@iina Meta+D find-online-subs

SPACE cycle pause
#@iina p toggle-pip
t cycle ontop

j seek -5 exact
l seek 5 exact
Shift+j seek -1 exact
Shift+l seek 1 exact
Alt+j seek -30 exact
Alt+l seek 30 exact

LEFT seek -5 exact
RIGHT seek 5 exact
Shift+LEFT seek -1 exact
Shift+RIGHT seek 1 exact
Alt+LEFT seek -30 exact
Alt+RIGHT seek 30 exact

i add volume 5
k add volume -5
Shift+i add volume 1
Shift+k add volume -1
Alt+i add volume 10
Alt+k add volume -10

UP add volume 5
DOWN add volume -5
Shift+UP add volume 1
Shift+DOWN add volume -1
Alt+UP add volume 10
Alt+DOWN add volume -10

u multiply speed 0.9091
o multiply speed 1.1
Alt+u multiply speed 0.5
Alt+o multiply speed 2.0
1 set speed 0.5
2 set speed 0.75
3 set speed 1.0
4 set speed 1.5
5 set speed 2.0

m cycle mute

, frame-back-step
. frame-step

q add sub-delay -0.1
e add sub-delay 0.1
Shift+q add sub-delay -0.5
Shift+e add sub-delay 0.5
w set sub-delay 0

s cycle sub
a cycle audio
#@iina Shift+s sub-panel
#@iina Shift+a audio-panel
#@iina d playlist-panel
#@iina v video-panel
#@iina g chapter-panel

z add audio-delay -0.1
c add audio-delay 0.1
Shift+z add audio-delay -0.5
Shift+c add audio-delay 0.5
x set audio-delay 0

- add sub-scale -0.1
= add sub-scale +0.1

[ add sub-pos -1
] add sub-pos +1

h show-text "${filename}\n${time-pos} / ${duration}"
r cycle-values video-rotate 90 180 270 0

f cycle fullscreen
ESC set fullscreen no
ENTER set fullscreen yes

Meta+s screenshot
Meta+l ab-loop
Meta+L cycle-values loop "inf" "no"
Meta+. stop

n playlist-next
b playlist-prev
Shift+n add chapter 1
Shift+b add chapter -1
Meta+RIGHT playlist-next
Meta+LEFT playlist-prev

Ctrl+Meta+v cycle video
Ctrl+Meta+s cycle sub
Ctrl+Meta+a cycle audio
Ctrl+Meta+f cycle fullscreen
Ctrl+Meta+t cycle ontop

Meta+0 set window-scale 0.5
Meta+1 set window-scale 1
Meta+2 set window-scale 2

POWER quit
PLAY cycle pause
PAUSE cycle pause
PLAYPAUSE cycle pause
STOP quit
FORWARD seek 60
REWIND seek -60
NEXT playlist-next
PREV playlist-prev
VOLUME_UP add volume 2
VOLUME_DOWN add volume -2
MUTE cycle mute
CLOSE_WIN quit
