---
description: Finder
data:
  NSGlobalDomain:
    # Finder: show all filename extensions
    AppleShowAllExtensions: true

    # Enable spring loading for directories
    com.apple.springing.enabled: true

    # Remove the spring loading delay for directories
    com.apple.springing.delay: 0

  com.apple.desktopservices:
    # Force the Finder to gather all metadata first
    UseBareEnumeration: true

    # Avoid creation of .DS_Store files on network volumes.
    DSDontWriteNetworkStores: true
    DSDontWriteUSBStores: true

  com.apple.finder:
    # Finder: allow quitting via ⌘ + Q; doing so will also hide desktop icons
    QuitMenuItem: true

    # Disable Finder window animations and Get Info animations
    DisableAllAnimations: true

    # Finder > Preferences > Show warning before changing an extension
    FXEnableExtensionChangeWarning: false

    # Finder > Preferences > Show warning before removing from iCloud Drive
    FXEnableRemoveFromICloudDriveWarning: false

    # Finder > View > As List
    # Four-letter codes for the other view modes: `icnv`, `clmv`, `glyv`
    FXPreferredViewStyle: Nlsv

    # Don't show icons for hard drives, servers, and removable media on the desktop.
    ShowExternalHardDrivesOnDesktop: false
    ShowRemovableMediaOnDesktop: false
    ShowHardDrivesOnDesktop: false
    ShowMountedServersOnDesktop: false

    # Set ~ as the default location for new Finder windows
    NewWindowTarget: PfHm
    NewWindowTargetIsHome: true
    NewWindowTargetPath: "file://${HOME}/"

    # When performing a search, search the current folder by default
    FXDefaultSearchScope: SCcf

    # Expand the following File Info panes: "General", "Open with", and "Sharing & Permissions"
    FXInfoPanesExpanded:
      - General: true
      - OpenWith: true
      - Privileges: true

    # Keep folders on top when sorting by name
    _FXSortFoldersFirst: true

    # Disable sidebar: Recent Tags
    ShowRecentTags: false

    # Finder: hide status bar
    ShowStatusBar: false

    # Show path bar
    ShowPathbar: true

    # Open folders in new Finder tab instead of window
    FinderSpawnTab: true

    # Finder: show hidden files by default
    AppleShowAllFiles: true

    # Display full POSIX path as Finder window title
    _FXShowPosixPathInTitle: true

    # Disable the warning before emptying the Trash
    WarnOnEmptyTrash: false

    # Sort icon views by name, show item info and minimize grid spacing in icon views.
    DesktopViewSettings:
      IconViewSettings:
        arrangeBy: "name"
        gridSpacing: 1.0
        iconSize: 64.0
        showItemInfo: true

    FK_StandardViewSettings:
      IconViewSettings:
        arrangeBy: "name"
        gridSpacing: 1.0
        iconSize: 64.0
        showItemInfo: true

    StandardViewSettings:
      IconViewSettings:
        arrangeBy: "name"
        gridSpacing: 1.0
        iconSize: 64.0
        showItemInfo: true

  com.apple.screencapture:
    # Set the screenshot location:
    location: "~/Library/Mobile Documents/com~apple~CloudDocs/Screenshots"

    # Save screenshots in PNG format (other options: BMP, GIF, JPG, PDF, TIFF)
    type: png

  # Disable Resume system-wide
  com.apple.systempreferences:
    NSQuitAlwaysKeepsWindows: false




