#!/usr/bin/env bash

# See: https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#macos-big-sur---automatically-load-scripting-addition-on-startup
sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

yabai -m config window_topmost              off
yabai -m config window_opacity              off
yabai -m config window_shadow               off
yabai -m config window_border               off

