#!/usr/bin/env bash

# Loading Scripting Additions
# See: https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#macos-big-sur---automatically-load-scripting-addition-on-startup
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# Configuration
yabai -m config window_topmost              off
yabai -m config window_opacity              off
yabai -m config window_shadow               off
yabai -m config window_border               on

