accent: '#9000ff'
foreground: '#f1f1f1'
background: "#010101"
background_image:
  path: grain.jpg
  opacity: 15

details: darker
terminal_colors:
  normal:
    black: '#45475a'
    red: '#f38ba8'
    green: '#a6e3a1'
    yellow: '#f9e2af'
    blue: '#89b4fa'
    magenta: '#f5c2e7'
    cyan: '#94e2d5'
    white: '#bac2de'
  bright:
    black: '#585b70'
    red: '#f38ba8'
    green: '#a6e3a1'
    yellow: '#f9e2af'
    blue: '#89b4fa'
    magenta: '#f5c2e7'
    cyan: '#94e2d5'
    white: '#a6adc8'
