{...}: {
  home.shellAliases = {
    cat = "bat";
    grep = "rg";
    vi = "nvim";
    vim = "nvim";
    python = "python3";
    pip = "pip3";
    rm = "gtrash put";
    "rm!" = "/bin/rm";
    md = "mkdir -p";
    ml = "ln -s";
    o = "open";
    oa = "open -a";
    oo = "open .";
    e = "code --wait";
    edit = "code --wait";
    ee = "code --wait .";
    lg = "lazygit";
    ld = "lazydocker";
    l = "eza -a --group --header --group-directories-first --git --icons --hyperlink";
    la = "eza -a --group --header --group-directories-first --git --icons --oneline --hyperlink";
    ll = "eza -a --group --header --group-directories-first --git --icons --long --hyperlink";
    lo = "eza -a --group --header --group-directories-first --git --icons --oneline --hyperlink";
    lt = "eza -a --group --header --group-directories-first --git --icons --tree --hyperlink";
    lt1 = "eza -a --group --header --group-directories-first --git --icons --tree --level=1 --hyperlink";
    lt2 = "eza -a --group --header --group-directories-first --git --icons --tree --level=2 --hyperlink";
    lt3 = "eza -a --group --header --group-directories-first --git --icons --tree --level=3 --hyperlink";
    ad = "ouch decompress";
    al = "ouch list";
    ma = "ouch compress";
    trf = "gtrash find";
    trg = "gtrash restore-group";
    trl = "gtrash find -n 1 --restore -f";
    trr = "gtrash restore";
    trs = "gtrash summary";
    fc = "fzf";
    ip = "dig +short myip.opendns.com @resolver1.opendns.com";
    localip = "ipconfig getifaddr en0";
    whichis = "type -a --path";
    sp = "speedtest";
    cl = "clear";
  };
}
